//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuildTray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamBuildTray.Resources.ResourcesMain", typeof(ResourcesMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window.
        /// </summary>
        internal static string MainWindow_CloseTooltip {
            get {
                return ResourceManager.GetString("MainWindow_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter build list.
        /// </summary>
        internal static string MainWindow_ConfigureTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ConfigureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Build Tray.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} built successfully.
        /// </summary>
        internal static string NotifierWindow_BuildPassed {
            get {
                return ResourceManager.GetString("NotifierWindow_BuildPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} broke {1}.
        /// </summary>
        internal static string NotifierWindow_FailedBuild {
            get {
                return ResourceManager.GetString("NotifierWindow_FailedBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started {1} build.
        /// </summary>
        internal static string NotifierWindow_InProgress {
            get {
                return ResourceManager.GetString("NotifierWindow_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definitions found due to incorrect project name or insufficient permissions..
        /// </summary>
        internal static string NotifierWindow_NoDefinitions {
            get {
                return ResourceManager.GetString("NotifierWindow_NoDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} queued {1}.
        /// </summary>
        internal static string NotifierWindow_Queued {
            get {
                return ResourceManager.GetString("NotifierWindow_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotifierWindow_Title {
            get {
                return ResourceManager.GetString("NotifierWindow_Title", resourceCulture);
            }
        }
    }
}
